### ISSUE TITLE
TV-B-GONE not working

### ISSUE THREAD

**Issue by JCtronics** [n0xa/m5stick-nemo#183]
Not sure if software problem or hardware. I’ve tried 3 TV’s so far and nothing..

**Comment by naturalstate** [comment]
I don't think it works on a lot of TV's anymore. I built a stand alone  TVbgone and it didn't work either on three TV's in the house.

**Comment by IsaacLouzeiro** [comment]
A month ago I've created a new function called "Custom" at TV B Gone, because I was with this same problem. In this function I've put a way to add other devices in a friendly way. Is your TV LG Brand? In LG TVs it was not working as well, until I added this function. Now it's working. You can see this function in "Develop" Branch.
